[package]
name = "sui_ibt"
edition = "2024"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/devnet" }

[addresses]
sui_ibt = "0x0"

[environments]
devnet = "a9149565"
